version: '3.1'
services:
  testing:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      greptimedb:
        condition: service_healthy
      extension:
        condition: service_started
    volumes:
      - type: volume
        source: cache
        target: /var/data
    links:
      - mysql
      - greptimedb
  extension:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - "GO_BUILDER=ghcr.io/linuxsuren/library/golang:1.22"
        - "BASE_IMAGE=ghcr.io/linuxsuren/library/alpine:3.12"
        - GOPROXY=${GOPROXY}
#    ports:
#      - "7071:7071"
  mysql:
    image: ghcr.io/linuxsuren/library/mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atest
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/3306"]
      interval: 3s
      timeout: 180s
      retries: 30
#    ports:
#      - "3306:3306"

  tdengine:
    image: ghcr.io/linuxsuren/tdengine/tdengine:3.3.3.0
    environment:
      TAOS_ROOT_PASSWORD: "root"
#    ports:
#      - "6030:6030"       # REST API port
#      - "6031:6031"       # client port
#      - "6041:6041"       # cluster port

  greptimedb:
    image: ghcr.io/linuxsuren/greptime/greptimedb:v0.12.0
    command: standalone start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
#    ports:
#      - "4002:4002"
volumes:
  cache:
